version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run: python setup.py sdist bdist_wheel
      - persist_to_workspace:
        root: /tmp
        paths:
          - workspace
  test-release:
    docker:
      - image: circleci/python:2.7
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
        at: /tmp
      - run: twine upload -p $PYPI_USERNAME -u $PYPI_PASSWORD --repository-url https://test.pypi.org/legacy/ dist/*
  release:
    docker:
      - image: circleci/python:2.7
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
        at: /tmp
      - run: twine upload -p $PYPI_USERNAME -u $PYPI_PASSWORD --repository-url https://upload.pypi.org/legacy/ dist/*

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test-release:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
