version: 2
jobs:
  test-python2:
    docker:
      - image: circleci/python:2.7
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run: sudo python setup.py develop
      - run: TENSORDASH_API=https://1072qzavta.execute-api.us-east-1.amazonaws.com/dev/config python test/test.py
      - persist_to_workspace:
          root: /tmp
          paths:
            - workspace
  test-python3:
    docker:
      - image: circleci/python:3.6
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run: sudo python setup.py develop
      - run: TENSORDASH_API=https://1072qzavta.execute-api.us-east-1.amazonaws.com/dev/config python test/test.py
  test-release:
    docker:
      - image: circleci/python:2.7
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp
      - run: python setup.py sdist bdist_wheel
      - run: python -m pip install --user twine==1.11.0
      - run: python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --repository-url https://test.pypi.org/legacy/ dist/*
  release:
    docker:
      - image: circleci/python:2.7
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp
      - run: python setup.py sdist bdist_wheel
      - run: python -m pip install --user twine==1.11.0
      - run: python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --repository-url https://upload.pypi.org/legacy/ dist/*

workflows:
  version: 2
  build-and-release:
    jobs:
      - test-python2:
          filters:
            tags:
              only: /.*/
      - test-python3:
          filters:
            tags:
              only: /.*/
      - test-release:
          requires:
            - test-python2
            - test-python3
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - release:
          requires:
            - test-python2
            - test-python3
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
